$axure.loadCurrentPage({
  "url":"home_1.html",
  "generationDate":new Date(1498124072830.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"018f1a93309f4144b9c62e128829fad0",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6f474bfcc0534c78ac568a166479e0c1",
          "label":"Show Product Details",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":60},
            "size":{
              "width":51,
              "height":50}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"48e3a40569794ced8767b6d237c8c8f1",
              "label":"Open Panel",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cc96bdac277041c5bac83d3e6e992825",
                  "label":"",
                  "parentDynamicPanel":"6f474bfcc0534c78ac568a166479e0c1",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":30,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"55ce52dcffac4455b088ac45187b5752",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6f474bfcc0534c78ac568a166479e0c1",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":30,
                          "height":30},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Show Product Details to Close Panel show if hidden",
                              "panelsToStates":[{
                                  "panelPath":["6f474bfcc0534c78ac568a166479e0c1"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/product/plus1_u185.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"2831fb4ae3cc4990b17e9f2c17f204c0",
              "label":"Close Panel",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"61162e2915b241fdb17930389a9a85bf",
                  "label":"",
                  "parentDynamicPanel":"6f474bfcc0534c78ac568a166479e0c1",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":20,
                      "height":20},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"289185588dd44f06b4aacc6002706883",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6f474bfcc0534c78ac568a166479e0c1",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":20,
                          "height":20},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Show Product Details to Open Panel show if hidden",
                              "panelsToStates":[{
                                  "panelPath":["6f474bfcc0534c78ac568a166479e0c1"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/product/plus2_u183.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "6f474bfcc0534c78ac568a166479e0c1":{
      "scriptId":"u0"},
    "cc96bdac277041c5bac83d3e6e992825":{
      "scriptId":"u1"},
    "55ce52dcffac4455b088ac45187b5752":{
      "scriptId":"u2"},
    "61162e2915b241fdb17930389a9a85bf":{
      "scriptId":"u3"},
    "289185588dd44f06b4aacc6002706883":{
      "scriptId":"u4"}}});